################################################################################
#
# rockchip-rkbin
#
################################################################################

ROCKCHIP_RKBIN_CUSTOM_VERSION = $(call qstrip,$(BR2_PACKAGE_ROCKCHIP_RKBIN_CUSTOM_VERSION))
ROCKCHIP_RKBIN_CUSTOM_SITE = https://github.com/rockchip-linux/rkbin.git
ROCKCHIP_RKBIN_CUSTOM_SITE_METHOD = git
ROCKCHIP_RKBIN_CUSTOM_LICENSE = PROPRIETARY
ROCKCHIP_RKBIN_CUSTOM_LICENSE_FILES = LICENSE

ROCKCHIP_RKBIN_CUSTOM_INSTALL_IMAGES = YES
ROCKCHIP_RKBIN_CUSTOM_INSTALL_TARGET = NO

ROCKCHIP_RKBIN_CUSTOM_BL31_FILENAME = $(call qstrip,$(BR2_PACKAGE_ROCKCHIP_RKBIN_CUSTOM_BL31_FILENAME))
ROCKCHIP_RKBIN_CUSTOM_TPL_FILENAME = $(call qstrip,$(BR2_PACKAGE_ROCKCHIP_RKBIN_CUSTOM_TPL_FILENAME))
ROCKCHIP_RKBIN_CUSTOM_TEE_FILENAME = $(call qstrip,$(BR2_PACKAGE_ROCKCHIP_RKBIN_CUSTOM_TEE_FILENAME))

define ROCKCHIP_RKBIN_CUSTOM_INSTALL_IMAGES_CMDS
	$(foreach f, \
		$(ROCKCHIP_RKBIN_CUSTOM_BL31_FILENAME) \
		$(ROCKCHIP_RKBIN_CUSTOM_TPL_FILENAME) \
		$(ROCKCHIP_RKBIN_CUSTOM_TEE_FILENAME) \
		, \
		$(INSTALL) -D -m 0644 -t $(BINARIES_DIR) $(@D)/$(f)
	)
endef

$(eval $(generic-package))
